# -*- coding: utf-8 -*-
"""02_Source_Separation_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TSr2__FCFzbyqWRcYDK3rtmyQUiGrKuT

# **Source separation with Demucs**
In this notebook, we will test [Demucs](https://github.com/facebookresearch/demucs), which is a state-of-the-art deep learning model developed by Meta AI for music source separation. It is designed to take a mixed audio track and separate it into its constituent instrumental stems, such as drums, bass, other, vocals, guitar and piano (in it's 6-stems version).

## Import and Utilities
"""

# =================================================================
#                 GOOGLE COLAB ENVIRONMENT SETUP
# =================================================================
from google.colab import drive
drive.mount('/content/drive')

import os
PROJECT_PATH = '/content/drive/MyDrive/audio-restoration-musicgen'
os.makedirs(PROJECT_PATH, exist_ok = True)
os.chdir(PROJECT_PATH)

# Install Demucs and other required libraries
!pip install -q demucs soundfile librosa matplotlib
!pip install -U git+https://github.com/facebookresearch/demucs#egg=demucs

# ==========================
#          IMPORT
# ==========================
import torch
import librosa
import numpy as np
import soundfile as sf
import matplotlib.pyplot as plt
from IPython.display import Audio, display

# ==========================================================
#              VERIFYNG IF GPU IS AVAILABLE
# ==========================================================
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'

"""## Set up for source separation"""

###### LOADING AUDIO ######

# Define paths to the data folders
folder_original = "data/generated/"

# Set up for saving audio's amplitudes and sampling rates
amplitudes_orig = {}
sampling_rates = {}

# Get the list of filenames
audio_filenames = sorted([f for f in os.listdir(folder_original) if f.endswith('.wav')])

print("Loading original audio files...")
for filename in audio_filenames:
    path_orig = os.path.join(folder_original, filename)
    amp_orig, sr = librosa.load(path_orig, sr=None)
    amplitudes_orig[filename] = amp_orig
    sampling_rates[filename] = sr
print("Data loading complete.")

###### LOADING DEMUCS MODEL ######

from demucs.apply import apply_model
from demucs.pretrained import get_model

print('loading model Demucs ...\n')
demucs = get_model('htdemucs_6s')
demucs_sr = demucs.samplerate
demucs.to(device)
print(f"\nmodel Demucs loaded successfully\nsampling rate: {demucs_sr} Hz.")

###### DEMUCS FUNCTION ######

def demucs_apply(model, original_amplitude, original_sr):

    """
    Applies the Demucs model to a noisy audio signal.

    Args:
        model: The pre-loaded Demucs model object.
        original_amplitude (np.ndarray): The NumPy array of the noisy audio.
        original_sr (int): The original sampling rate of the audio (e.g., 32000).

    Returns:
        6 stems: bass, drums, other, vocals, guitar and piano.
    """

    model_sr = model.samplerate
    resampled_amp = librosa.resample(original_amplitude, orig_sr=original_sr, target_sr=model_sr) # Demucs works with audio at 44100 Hz.

    # Prepare a fake stereo tensor as required by the 6-stem model
    mono_tensor = torch.tensor(resampled_amp).unsqueeze(0).to(device)
    stereo_tensor = mono_tensor.repeat(2, 1).unsqueeze(0)
    # shape [1, 2, samples] ([batch_size, channels, samples]) is required because Demucs was trained almost exclusively on stereo music.

    print("Source separation in progress ...")
    with torch.no_grad(): # disables the calculation of gradients
        separated_sources = apply_model(model, stereo_tensor, device=device)[0]
        # separated_sources has shape [6, 2, samples]. Indices on dim=0 are as follows:
        # 0: drums, 1: bass, 2: other, 3: vocals, 4: guitar, 5: piano
        # indices on dim=1 are for left and right channels.

    drums, bass, other, vocals, guitar, piano = separated_sources

    # ----- convert to numpy array and move to cpu -----
    drums_np = drums.cpu().numpy()
    bass_np = bass.cpu().numpy()
    other_np = other.cpu().numpy()
    vocals_np = vocals.cpu().numpy()
    guitar_np = guitar.cpu().numpy()
    piano_np = piano.cpu().numpy()

    # ----- convert to mono -----
    drums_mono = drums_np.mean(axis=0)
    bass_mono = bass_np.mean(axis=0)
    other_mono = other_np.mean(axis=0)
    vocals_mono = vocals_np.mean(axis=0)
    guitar_mono = guitar_np.mean(axis=0)
    piano_mono = piano_np.mean(axis=0)

    return drums_mono, bass_mono, other_mono, vocals_mono, guitar_mono, piano_mono

"""## Source Separation"""

stems_path = 'data/stems/original/'     # defining the directory
os.makedirs(stems_path, exist_ok=True)

for i, (filename, amp) in enumerate(amplitudes_orig.items()):
    sr = sampling_rates[filename]
    folder = os.path.join(stems_path, f'sample_{i+1}')  # defining the directory for each audio
    os.makedirs(folder, exist_ok=True)

    print(f'\nProcessing sample {i+1}: {filename}')
    drums, bass, other, vocals, guitar, piano = demucs_apply(demucs, amp, sr)
    print(f"Process completed successfully. Stems have been saved in {folder}")

    print('\n----- original audio -----')
    display(Audio(data=amp, rate=sr))
    print('listen to the stems:')

    print('----- drums -----')
    drums_path = os.path.join(folder, f'drums.wav')
    sf.write(drums_path, drums, demucs_sr)
    display(Audio(data=drums, rate=demucs_sr))

    print('----- bass -----')
    bass_path = os.path.join(folder, f'bass.wav')
    sf.write(bass_path, bass, demucs_sr)
    display(Audio(data=bass, rate=demucs_sr))

    print('----- other -----')
    other_path = os.path.join(folder, f'other.wav')
    sf.write(other_path, other, demucs_sr)
    display(Audio(data=other, rate=demucs_sr))

    print('----- vocals -----')
    vocals_path = os.path.join(folder, f'vocals.wav')
    sf.write(vocals_path, vocals, demucs_sr)
    display(Audio(data=vocals, rate=demucs_sr))

    print('----- guitar -----')
    guitar_path = os.path.join(folder, f'guitar.wav')
    sf.write(guitar_path, guitar, demucs_sr)
    display(Audio(data=guitar, rate=demucs_sr))

    print('----- piano -----')
    piano_path = os.path.join(folder, f'piano.wav')
    sf.write(piano_path, piano, demucs_sr)
    display(Audio(data=piano, rate=demucs_sr))