# -*- coding: utf-8 -*-
"""03_Stems_Denoising_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5wiRIrZ4dPJzKPKgTpoiPo-kMnqCEBN

# **Stems denoising with Noisereduce**
In this notebook we will use [Noisereduce](https://github.com/timsainb/noisereduce/blob/master/README.md#steps-of-the-stationary-noise-reduction-algorithm), wich is a noise reduction algorithm in python that reduces noise in time-domain signals. We can summarize the noisereduce process in these steps:  


1.   **Input:**


*   signal;
*   optionally, a noise-only fragment (noise_clip)


2. **Transformation:** transform the signal from the time domain to the frequency domain (via STFT → Short-Time Fourier Transform).
3.   **Frequency analysis:** the spectrogram is calculated: it represents how the signal energy is distributed across the various frequencies over time.

4. **Noise estimation:**


*   if you have provided a noise_clip, it is used to estimate the noise profile;
*   if you don't provide it, the library tries to estimate it automatically by analyzing the signal parts.

5. **Mask construction (spectral gating):** for each frequency band, a dynamic threshold is set based on the estimated noise level. A mask is created that lets signals above the threshold pass and attenuates those below.
This is different from the classic "cutting all low frequencies" because the threshold varies with frequency.

6. **Reconstruction:** the mask is applied to the spectrogram and the inverse time transform (ISTFT) is performed to return the signal over time.
  

Here you can try both methods:
* Since our audio doesn't contain any speech, Demucs will insert all the noise and artifacts present in the track into the stem vocals. So, a good idea would be to use each audio's vocals as its noise_clip.
* You can provide the algorithm with just the signal track and let it recognize the noise to eliminate.

## Import and Utilities
"""

# =================================================================
#                 GOOGLE COLAB ENVIRONMENT SETUP
# =================================================================
from google.colab import drive
drive.mount('/content/drive')

import os
PROJECT_PATH = '/content/drive/MyDrive/audio-restoration-musicgen'
os.chdir(PROJECT_PATH)

# Install Noisereduce
!pip install noisereduce
!pip install -q mir_eval librosa soundfile

# ==========================
#          IMPORT
# ==========================
import torch
import librosa
import numpy as np
import soundfile as sf
import matplotlib.pyplot as plt
from IPython.display import Audio, display
import noisereduce as nr
import librosa.display
import mir_eval
from glob import glob

"""## Stems Denoising"""

stems_folder = 'data/stems/original/'
denoised_stems_folder = 'data/stems/denoised/'    # defining the directory for denoised stems
os.makedirs(denoised_stems_folder, exist_ok=True)

samples = os.listdir(stems_folder)
stems = ['drums.wav', 'bass.wav', 'other.wav', 'guitar.wav', 'piano.wav']

data = {} # here we're saving information about stems amplitudes for each audio

for sample in samples:

    sample_stems_folder = os.path.join(stems_folder, sample)
    sample_denoised_stems_folder = os.path.join(denoised_stems_folder, sample)
    os.makedirs(sample_denoised_stems_folder, exist_ok=True) # defining the directory for each audio

    data[sample] = {}

    ############### use this part of code only if you want to use a noise clip ###############
    noise_clip, noise_sr = librosa.load(f'data/stems/original/{sample}/vocals.wav', sr=None)
    duration_seconds = 10
    start_second = duration_seconds - 5    # we take the last 5 seconds
    end_second = duration_seconds
    start_sample = int(start_second * noise_sr)
    end_sample = int(end_second * noise_sr)
    noise_clip = noise_clip[start_sample : end_sample]
    ##########################################################################################

    for stem in stems:

        stem_path = os.path.join(sample_stems_folder, stem)
        denoised_stem_path = os.path.join(sample_denoised_stems_folder, stem)

        stem_amp, stem_sr = librosa.load(stem_path, sr = None)

        denoised_stem_amp = nr.reduce_noise(

                y=stem_amp,                   # audio signal on which you want to reduce noise.

                sr=stem_sr,

                y_noise=noise_clip,          # remove/put the comment marker to use/not use a noise clip during noise reduction

                stationary=True,              # it tells the algorithm that the noise is stationary, meaning it remains similar over time.
                                              # If it were False, it would use a more flexible but also more cumbersome method, suited to time-varying noise.

                prop_decrease=0.9             # Controls how much noise is removed. It's a value between 0 and 1:
                                              #  1.0 → removes all estimated noise (may degrade quality).
                                              #  0.0 → removes nothing.
                                              #  0.9 → removes 90% of the estimated noise, leaving some for a more natural sound.
            )

        data[sample][stem] = denoised_stem_amp

        sf.write(denoised_stem_path, denoised_stem_amp, stem_sr)

        print(f'\n----- original {stem} for {sample} -----')
        display(Audio(data=stem_amp, rate=stem_sr))

        print(f'----- denoised {stem} for {sample} -----')
        display(Audio(data=denoised_stem_amp, rate=stem_sr))
    print('-------------------------------------------\n')