# -*- coding: utf-8 -*-
"""03_Stems_Denoising.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxt7B5psNttckoD6NbU1AslD1ZEselhm

# **Stems denoising with Noisereduce**
In this notebook we will use [Noisereduce](https://github.com/timsainb/noisereduce/blob/master/README.md#steps-of-the-stationary-noise-reduction-algorithm), wich is a noise reduction algorithm in python that reduces noise in time-domain signals. We can summarize the noisereduce process in these steps:  


1.   **Input:**


*   signal;
*   optionally, a noise-only fragment (noise_clip)


2. **Transformation:** transform the signal from the time domain to the frequency domain (via STFT → Short-Time Fourier Transform).
3.   **Frequency analysis:** the spectrogram is calculated: it represents how the signal energy is distributed across the various frequencies over time.

4. **Noise estimation:**


*   if you have provided a noise_clip, it is used to estimate the noise profile;
*   if you don't provide it, the library tries to estimate it automatically by analyzing the signal parts.

5. **Mask construction (spectral gating):** for each frequency band, a dynamic threshold is set based on the estimated noise level. A mask is created that lets signals above the threshold pass and attenuates those below.
This is different from the classic "cutting all low frequencies" because the threshold varies with frequency.

6. **Reconstruction:** the mask is applied to the spectrogram and the inverse time transform (ISTFT) is performed to return the signal over time.
  

Here you can try both methods:
* Since our audio doesn't contain any speech, Demucs will insert all the noise and artifacts present in the track into the stem vocals. So, a good idea would be to use each audio's vocals as its noise_clip.
* You can provide the algorithm with just the signal track and let it recognize the noise to eliminate.

## Import and Utilities
"""

# =================================================================
#                 GOOGLE COLAB ENVIRONMENT SETUP
# =================================================================
from google.colab import drive
drive.mount('/content/drive')

import os
PROJECT_PATH = '/content/drive/MyDrive/audio-restoration-musicgen'
os.chdir(PROJECT_PATH)

# Install Noisereduce
!pip install noisereduce
!pip install -q mir_eval librosa soundfile

# ==========================
#          IMPORT
# ==========================
import torch
import librosa
import numpy as np
import soundfile as sf
import matplotlib.pyplot as plt
from IPython.display import Audio, display
import noisereduce as nr
import librosa.display
import mir_eval
from glob import glob

"""## Stems Denoising"""

stems_folder = 'data/stems/original/'
denoised_stems_folder = 'data/stems/denoised/'    # defining the directory for denoised stems
os.makedirs(denoised_stems_folder, exist_ok=True)

samples = os.listdir(stems_folder)
stems = ['drums.wav', 'bass.wav', 'other.wav', 'guitar.wav', 'piano.wav']

data = {} # here we're saving information about stems amplitudes for each audio

for sample in samples:

    sample_stems_folder = os.path.join(stems_folder, sample)
    sample_denoised_stems_folder = os.path.join(denoised_stems_folder, sample)
    os.makedirs(sample_denoised_stems_folder, exist_ok=True) # defining the directory for each audio

    data[sample] = {}

    ############### use this part of code only if you want to use a noise clip ###############
    noise_clip, noise_sr = librosa.load(f'data/stems/original/{sample}/vocals.wav', sr=None)
    duration_seconds = 10
    start_second = duration_seconds - 5    # we take the last 5 seconds
    end_second = duration_seconds
    start_sample = int(start_second * noise_sr)
    end_sample = int(end_second * noise_sr)
    noise_clip = noise_clip[start_sample : end_sample]
    ##########################################################################################

    for stem in stems:

        stem_path = os.path.join(sample_stems_folder, stem)
        denoised_stem_path = os.path.join(sample_denoised_stems_folder, stem)

        stem_amp, stem_sr = librosa.load(stem_path, sr = None)

        denoised_stem_amp = nr.reduce_noise(

                y=stem_amp,                   # audio signal on which you want to reduce noise.

                sr=stem_sr,

                y_noise=noise_clip,          # remove/put the comment marker to use/not use a noise clip during noise reduction

                stationary=True,              # it tells the algorithm that the noise is stationary, meaning it remains similar over time.
                                              # If it were False, it would use a more flexible but also more cumbersome method, suited to time-varying noise.

                prop_decrease=0.9             # Controls how much noise is removed. It's a value between 0 and 1:
                                              #  1.0 → removes all estimated noise (may degrade quality).
                                              #  0.0 → removes nothing.
                                              #  0.9 → removes 90% of the estimated noise, leaving some for a more natural sound.
            )

        data[sample][stem] = denoised_stem_amp

        sf.write(denoised_stem_path, denoised_stem_amp, stem_sr)

        print(f'\n----- original {stem} for {sample} -----')
        display(Audio(data=stem_amp, rate=stem_sr))

        print(f'----- denoised {stem} for {sample} -----')
        display(Audio(data=denoised_stem_amp, rate=stem_sr))
    print('-------------------------------------------\n')

"""## Visual Analysis
This section is dedicated to a visual comparison between the original and clean stems. In particular, we will analyze:
- the waveforms compared;
- the waveform of the removed noise (original - denoised);
- the spectrograms compared.

What we would like to see is a cleaner waveform and a less noisy spectrogram.
"""

sample = "sample_3"   # Select the audio you want to see graphs for
raw_dir = f"data/stems/original/{sample}"
clean_dir = f"data/stems/denoised/{sample}"

files = sorted([f for f in os.listdir(clean_dir)])

for fname in files:

    raw_path = os.path.join(raw_dir, fname)
    clean_path = os.path.join(clean_dir, fname)

    raw, raw_sr = librosa.load(raw_path, sr = None)
    clean, clean_sr = librosa.load(clean_path, sr = None)

    L = min(len(raw), len(clean))
    raw = raw[:L]
    clean = clean[:L]

    noise = clean - raw

    fig, axs = plt.subplots(2,2, figsize=(14,6))
    axs = axs.flatten()
    t = np.arange(L) / raw_sr

    axs[0].set_title(f"{fname} - waveform: raw vs clean")
    axs[0].plot(t, raw, linewidth=0.6)
    axs[0].plot(t, clean, linewidth=0.6, alpha=0.8)
    axs[0].legend(["raw","clean"])

    axs[1].set_title("difference waveform (clean - raw)")
    axs[1].plot(t, noise, linewidth=0.5)
    axs[1].axhline(0, color='k', linewidth=0.5)

    D1 = librosa.amplitude_to_db(np.abs(librosa.stft(raw, n_fft=2048)), ref=np.max)
    img = librosa.display.specshow(D1, sr=clean_sr, x_axis='time', y_axis='log', ax=axs[2])
    axs[2].set_title("Spectrogram (raw)")
    fig.colorbar(img, ax=axs[2], format="%+2.f dB")

    D2 = librosa.amplitude_to_db(np.abs(librosa.stft(clean, n_fft=2048)), ref=np.max)
    img = librosa.display.specshow(D2, sr=clean_sr, x_axis='time', y_axis='log', ax=axs[3])
    axs[3].set_title("Spectrogram (clean)")
    fig.colorbar(img, ax=axs[3], format="%+2.f dB")

    plt.tight_layout()
    plt.show()

    print('-' * 160)
    print('\n')

"""## DNSMOS

This part of the notebook is dedicated to the evaluation of clean stems. To do this, we'll use [DNSMOS](https://github.com/microsoft/DNS-Challenge/tree/master/DNSMOS) (Deep Noise Suppression Mean Opinion Score), a no-reference audio quality metric developed by Microsoft, based on deep learning models trained on thousands of human evaluations.
It provides three main scores—SIG (signal quality), BAK (background noise quality), and OVRL (overall quality)—on a scale of 1.0 to 5.0, where higher scores indicate clearer, cleaner, and more enjoyable audio.
It's particularly useful for evaluating the improvement of model-generated audio (e.g., MusicGen) without the need for a "perfect" reference.
"""

# Commented out IPython magic to ensure Python compatibility.
###### INSTALLING DNSMOS ######
# %cd /content
!rm -rf DNS-Challenge
!git clone https://github.com/microsoft/DNS-Challenge.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/DNS-Challenge/DNSMOS/DNSMOS
!pip install onnxruntime librosa numpy

###### DNSMOS CLASS ######

import onnxruntime as ort #import the onnxruntime library which is used to run machine learning models saved in .onnx format — such as those used by DNSMOS.

MODEL_PATH = "/content/DNS-Challenge/DNSMOS/DNSMOS/sig_bak_ovr.onnx" # This model estimates SIG (Signal), BAK (Background), and OVRL (Overall) — three quality scores.

TARGET_LENGTH = 144160  # Defines how many samples the model's input audio should have.
                        # Since the model was trained on blocks of 144,160 samples at 16 kHz, each audio MUST be exactly this long.

class DNSMOS_New:
    def __init__(self, model_path):
        self.session = ort.InferenceSession(model_path) # Loads the machine learning model from the .onnx file and prepares it for inference (i.e., making predictions).

    def compute_dnsmos(self, audio_path):
        '''
        Args: file audio path
        Returns: quality scores
        '''
        audio, sr = librosa.load(audio_path, sr=16000, mono=True)

        if len(audio) < TARGET_LENGTH:                                              # Checks whether the audio is shorter or longer than TARGET_LENGTH (144160):
            audio = np.pad(audio, (0, TARGET_LENGTH - len(audio)), mode='constant') # If shorter, append zeros to the end (np.pad) to reach the required length.
        else:
            audio = audio[:TARGET_LENGTH]                                           # If longer, trim the audio to the first 144160 samples.

        input_data = np.expand_dims(audio.astype(np.float32), axis=0) # Transform the 1D array ([144160]) into a 2D array ([1, 144160]) because the
                                                                      # model expects a batch of inputs — even if you only pass one.

        input_name = self.session.get_inputs()[0].name    # This is used to correctly pass data to the template in the next row.

        output_names = [o.name for o in self.session.get_outputs()]  # It asks the model what outputs it produces.
                                                                     # In this case, the model returns an array with 3 values: [SIG, BAK, OVRL]

        outputs = self.session.run(output_names, {input_name: input_data})  # Run the model! Pass input_data and get the scores back.

        sig, bak, ovr = outputs[0][0]  # These are the scores that interest us

        return {
            "SIG": float(sig),
            "BAK": float(bak),
            "OVRL": float(ovr)
        }

dnsmos = DNSMOS_New(MODEL_PATH)

def dnsmos_scores(filepath, name="Audio"):
    '''
    Args: audio filepath

    -> Prints the results legibly

    Returns: the OVRL score (useful for comparisons)
    '''

    print(f"📈 Analyzing {name} stem...")

    scores = dnsmos.compute_dnsmos(filepath)

    ovrl = scores['OVRL']
    sig = scores['SIG']
    bak = scores['BAK']

    print(f"   OVRL (Overall): {ovrl:.4f}/5")
    print(f"   SIG (Signal): {sig:.4f}/5")
    print(f"   BAK (Backround): {bak:.4f}/5\n")

    return ovrl, sig, bak

###### EVALUATION ######

sample = "sample_4"  # choose a sample to evaluate

folder_orig = os.path.join(PROJECT_PATH, f"data/stems/original/{sample}")
folder_impr = os.path.join(PROJECT_PATH, f"data/stems/denoised/{sample}")

stems = sorted(os.listdir(folder_impr))

improved = 0

for stem in stems:

    path_orig = os.path.join(folder_orig, stem)
    path_impr = os.path.join(folder_impr, stem)

    print("\n" + "="*50)
    print(" "*17 + f"stem: {stem}")
    print("="*50)

    ovrl_orig, sig_orig, bak_orig = dnsmos_scores(path_orig, "Original")
    ovrl_impr, sig_impr, bak_impr = dnsmos_scores(path_impr, "Denoised")

    delta_ovrl, delta_sig, delta_bak = (ovrl_impr - ovrl_orig), (sig_impr - sig_orig), (bak_impr - bak_orig)

    print("\n------📈 FINAL RESULTS 📈------")
    if delta_sig >= 0:
        print(f"SIG: +{delta_sig:.4f} -> useful signal preserved or improved✅")
    else:
        print(f"SIG: {delta_sig:.4f} -> the denoiser removed useful signal❌")

    if delta_bak > 0:
        print(f"BAK: +{delta_bak:.4f} -> noise and artifacts are reduced✅")
    else:
        print(f"BAK: {delta_bak:.4f} -> noise was not removed or artifacts were added❌")

    if delta_ovrl > 0:
        print(f"OVRL: +{delta_ovrl:.4f} -> the overall quality is IMPROVED✅")
        improved += 1
    else:
        print(f"OVRL: {delta_ovrl:.4f} -> the overall quality has DETERIORATED or remained UNCHANGED❌")


print('\n------------------------------------------------------------------------------------------------')
print(f"\n-> {improved} out of {len(stems)} improved stems")

